defaults:
  - array: ns_ppc
  - rsa/models: able_bodied_pcip
  - override hydra/job_logging: colorlog
  - _self_ # Override defaults list with below values

metrics:
  similarity: cosine_cov

rdm_files: "multirun/2022-09-20/14-34-13/*/*_rdm.hdf5"
