defaults:
  - array: ns_ppc
  - rsa/models: muscle_somatotopic
  - matplotlib: base
  - override hydra/job_logging: colorlog
  - _self_ # Override defaults list with below values

rdm_files: "/path/to/repo/multirun/run_date/run_time/*/*_rdm.hdf5"
