defaults:
  - array: ns_ppc
  - rsa/models: able_bodied
  - override hydra/job_logging: colorlog
  - _self_ # Override defaults list with below values

metrics:
  similarity: cosine_cov

rdm_files: "/path/to/repo/multirun/run_date/run_time/*/*_rdm.hdf5"
