name: FingGrid
phase: Go
condition_order: [T, I, M, R, P, X]
condition_column: TrueClassStr
condition_column_alias: finger
label: ClosedLoop
dandiset: '000147'
dates: ???  # Missing value, must be populated prior to access
